services:
  vault:
    image: hashicorp/vault:1.15
    container_name: vault-server
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_ADDR: http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault-data:/vault/data
      - ./vault-config:/vault/config
      - ./certs:/vault/certs
    command: >
      sh -c "
      vault server -dev -dev-root-token-id=myroot -dev-listen-address=0.0.0.0:8200
      "